.\" manpage for py_platform
.\" groff, troff, whatever. view it with man
.TH py_platform 1 "03 Apr 2025" "main Branch" "py_platform Manual"

.SH NAME
.B py_platform 
- a command to get platform information

.SH SYNOPSIS
.B py_platform 
[ -h ] [ --help ] [ -f ] [ --freedesktop ] [ -a ] [ --android ] [ -w ] [ --win32 ] [ -d ] [ --darwin ] [ -i ] [ --ios ] [ -o ] [ --other ]

.SH DESCRIPTION
.B py_platform
is a Python script that shows information about your current system using the platform module.

.SH EXAMPLES
.B py_platform

.B py_platform
-fawdio /
.B py_platform
--freedesktop --android --win32 --darwin --ios --other

.B py_platform
-h /
.B py_platform
--help

.SH COMMAND LINE OPTIONS

.SS -h, --help
Shows help and exits

.SS -f, --freedesktop
Shows freedesktop.org OS release information from /etc/os-release in JSON in the normal output

.SS -a, --android
Shows Android information in the normal output

.SS -w, --win32
Shows win32 information in the normal output

.SS -d, --darwin
Shows Darwin information in the normal output

.SS -i, --ios
Shows iOS information in the normal output

.SS -o, --other
Shows other information in the normal output

.SH AUTHOR
.SS Owner / Creator
Nacroni - E-Mail: thespokenone209@hotmail.com

.SH COPYRIGHT
GPLv3 License, can be found in the source repo as 
.B LICENSE.md

Or you can find the license's current version online at 
.ul
https://www.gnu.org/licenses/gpl-3.0.en.html
.

Thank you, and have a very safe day.
